(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/uni-nav-bar/uni-nav-bar"],{"0c76":function(t,n,e){"use strict";(function(t){Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var i=function(){e.e("components/uni-nav-bar/uni-status-bar").then(function(){return resolve(e("7fb9"))}.bind(null,e)).catch(e.oe)},o={name:"UniNavBar",components:{statusBar:i},emits:["clickLeft","clickRight","clickTitle"],props:{title:{type:String,default:""},leftText:{type:String,default:""},rightText:{type:String,default:""},leftIcon:{type:String,default:""},rightIcon:{type:String,default:""},fixed:{type:[Boolean,String],default:!1},color:{type:String,default:"#000000"},backgroundColor:{type:String,default:"#FFFFFF"},statusBar:{type:[Boolean,String],default:!1},shadow:{type:[Boolean,String],default:!1},border:{type:[Boolean,String],default:!0}},mounted:function(){t.report&&""!==this.title&&t.report("title",this.title)},methods:{onClickLeft:function(){this.$emit("clickLeft")},onClickRight:function(){this.$emit("clickRight")},onClickTitle:function(){this.$emit("clickTitle")}}};n.default=o}).call(this,e("543d")["default"])},"402e":function(t,n,e){},ae56:function(t,n,e){"use strict";e.r(n);var i=e("0c76"),o=e.n(i);for(var u in i)["default"].indexOf(u)<0&&function(t){e.d(n,t,(function(){return i[t]}))}(u);n["default"]=o.a},bb32:function(t,n,e){"use strict";e.d(n,"b",(function(){return o})),e.d(n,"c",(function(){return u})),e.d(n,"a",(function(){return i}));var i={uniIcons:function(){return Promise.all([e.e("common/vendor"),e.e("components/uni-icons/uni-icons")]).then(e.bind(null,"2ba4"))}},o=function(){var t=this,n=t.$createElement;t._self._c},u=[]},d2de:function(t,n,e){"use strict";var i=e("402e"),o=e.n(i);o.a},f31d:function(t,n,e){"use strict";e.r(n);var i=e("bb32"),o=e("ae56");for(var u in o)["default"].indexOf(u)<0&&function(t){e.d(n,t,(function(){return o[t]}))}(u);e("d2de");var c,r=e("f0c5"),a=Object(r["a"])(o["default"],i["b"],i["c"],!1,null,"29137d8c",null,!1,i["a"],c);n["default"]=a.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/uni-nav-bar/uni-nav-bar-create-component',
    {
        'components/uni-nav-bar/uni-nav-bar-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("f31d"))
        })
    },
    [['components/uni-nav-bar/uni-nav-bar-create-component']]
]);
