/* eslint-disable import/no-commonjs */
module.exports = {
  defaultSeverity: 'error',
  plugins: ['stylelint-order'],
  extends: ['stylelint-config-standard', 'stylelint-prettier/recommended'], // 这是官方推荐的方式 'stylelint-prettier/recommended',
  rules: {
    'prettier/prettier': true,
    'block-no-empty': null,
    'selector-pseudo-class-no-unknown': null,
    'unit-no-unknown': [
      true,
      {
        ignoreUnits: ['rpx', 'rem', 'vw', 'vh', 'em'],
      },
    ],
    'declaration-block-single-line-max-declarations': null,
    'selector-pseudo-element-no-unknown': null,
    'declaration-block-no-shorthand-property-overrides': null,

    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: [
          'function',
          'each',
          'include',
          'mixin',
          '/deep/',
          'return',
          'extend',
          'at-root',
          'debug',
          'warn',
          'error',
          'if',
          'else',
          'for',
          'each',
          'while',
          'content',
          'media',
        ],
      },
    ],
    'no-duplicate-selectors': null,
    'no-empty-source': null,
    'no-descending-specificity': null,
    'font-family-no-missing-generic-family-keyword': null,
    'selector-type-no-unknown': [
      true,
      {
        ignoreTypes: ['/^page/'],
      },
    ],
    'no-eol-whitespace': null,
    // 指定声明块内属性的字母顺序
    'order/properties-order': [
      'content',
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'float',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'display',
      'flex',
      'flex-align',
      'flex-basis',
      'flex-direction',
      'flex-wrap',
      'flex-flow',
      'flex-shrink',
      'flex-grow',
      'flex-order',
      'flex-pack',
      'align-content',
      'align-items',
      'align-self',
      'justify-content',
      'order',
      'grid',
      'padding',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
      'margin',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'color',
      'font',
      'font-family',
      'font-size',
      'font-style',
      'font-weight',
      'line-height',
      'text-align',
      'text-indent',
      'text-shadow',
      'direction',
      'word-break',
      'letter-spacing',
      'vertical-align',
      'pointer-events',
      'box-sizing',
      'box-shadow',
      'overflow',
      'overflow-x',
      'overflow-y',
      'border-radius',
      'border',
      'border-color',
      'border-style',
      'border-width',
      'border-top',
      'border-top-color',
      'border-top-style',
      'border-top-width',
      'border-right',
      'border-right-color',
      'border-right-style',
      'border-right-width',
      'border-bottom',
      'border-bottom-color',
      'border-bottom-style',
      'border-bottom-width',
      'border-left',
      'border-left-color',
      'border-left-style',
      'border-left-width',
      'border-radius',
      'border-top-left-radius',
      'border-top-right-radius',
      'border-bottom-right-radius',
      'border-bottom-left-radius',
      'border-image',
      'border-image-source',
      'border-image-slice',
      'border-image-width',
      'border-image-outset',
      'border-image-repeat',
      'background',
      'background-repeat',
      'background-attachment',
      'background-position',
      'background-position-x',
      'background-position-y',
      'background-clip',
      'background-origin',
      'background-size',
      'transition',
      'transition-delay',
      'transition-timing-function',
      'transition-duration',
      'transition-property',
      'transform',
      'transform-origin',
      'perspective',
      'appearance',
      'animation',
      'animation-name',
      'animation-duration',
      'animation-play-state',
      'animation-timing-function',
      'animation-delay',
      'animation-iteration-count',
      'animation-direction',
      'animation-fill-mode',
      'opacity',
      'filter',
      'visibility',
      'z-index',
      'cursor',
      'touch-action',
      'caret-color',
      'table-layout',
      'table-layout',
      'empty-cells',
      'caption-side',
      'border-collapse',
      'border-spacing',
      '@include',
    ],
  },
};
